include:
  - local: '/.gitlab-ci/builds.yml'
    rules:
      - changes:
          - .gitlab-ci/builds.yml
          - flake.{nix,lock}
          - src/**/*.{cc,h}
          - include/**/*.h
          - CMakeLists.txt
          - cmake/**/*

  - local: '/.gitlab-ci/lints.yml'
    rules:
      - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
        changes:
          - src/**/*.{cc,h}
          - include/**/*.h
          - .clang-format

  - local: '/.gitlab-ci/tests.yml'
    rules:
      - if: '$CI_COMMIT_TAG || $CI_COMMIT_TITLE =~ /^chore\(semver\): Bump.*/'
      - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
        changes:
          - .gitlab-ci/tests.yml
          - flake.{nix,lock}
          - src/**/*.{cc,h}
          - include/**/*.h
          - CMakeLists.txt
          - cmake/**/*
          - tests/**/*

  - project: 'esab/abw/infra-and-test'
    ref: main
    file: '/.gitlab-ci/check-nix.yml'
    rules:
      - changes:
          - flake.{nix,lock}

  - project: 'esab/abw/infra-and-test'
    ref: main
    file:
      - '/.gitlab-ci/lint-commit.yml'
      - '/.gitlab-ci/k8-runner-defaults.yml'
      - '/.gitlab-ci/semver-version.yml'
      - '/.gitlab-ci/lint-python.yml'
      - '/.gitlab-ci/lint-markdown-cli2.yml'

  - project: 'esab/abw/infra-and-test'
    ref: main
    file: '/.gitlab-ci/lint-version.yml'
    inputs:
      job-rules:
        - if: '$CI_COMMIT_REF_PROTECTED == "true"'
        - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

  - project: 'esab/abw/infra-and-test'
    ref: main
    file: '/.gitlab-ci/build-nix.yml'
    inputs:
      verbose: true
      job-rules:
        - if: '$CI_COMMIT_TAG || $CI_COMMIT_TITLE =~ /^chore\(semver\): Bump.*/'
        - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
          changes:
            - flake.{nix,lock}
            - src/**/*.{cc,h}
            - include/**/*.h
            - CMakeLists.txt
            - cmake/**/*
            - version.txt

  - project: 'esab/abw/infra-and-test'
    ref: main
    file: '/.gitlab-ci/build-nix.yml'
    inputs:
      job-name: 'build-tests'
      job-artifacts-paths:
        - result/bin/adaptio-core-tests
        - result/bin/data-set-runner
        - result/bin/image-annotation
        - result/bin/test-images
        - result/lib/libadaptio-core.so
      job-rules:
        - if: '$CI_COMMIT_TAG && $CI_COMMIT_TITLE =~ /^chore\(semver\): Bump.*/'
        - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
          changes:
            - .gitlab-ci/tests.yml
            - flake.{nix,lock}
            - src/**/*.{cc,h}
            - include/**/*.h
            - CMakeLists.txt
            - cmake/**/*
            - tests/**/*
      nix-attribute: '.#adaptio-core-ci-dev'
      verbose: true

  - project: 'esab/abw/infra-and-test'
    ref: main
    file: '/.gitlab-ci/trigger-flake-update.yml'
    inputs:
      job-rules:
        - if: '$CI_COMMIT_TAG && $CI_COMMIT_TITLE =~ /^chore\(semver\): Bump.*/'
      target-project-name: 'adaptio'
      nix-input-name: 'adaptio-core-lib'

  - project: 'esab/abw/infra-and-test'
    ref: main
    file:
      - '/.gitlab-ci/update-flake-inputs.yml'
    inputs:
      job-rules:
        - if: '$CI_PIPELINE_SOURCE == "pipeline" && $CI_COMMIT_REF_PROTECTED == "true"'
        - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
          when: never
      ignore-breaking-change: true

workflow:
  name: '$PIPELINE_NAME'
  auto_cancel:
    on_new_commit: conservative
  rules:
    - if: '$CI_COMMIT_TAG && $CI_COMMIT_TITLE =~ /^chore\(semver\): Bump.*/'
      variables:
        PIPELINE_NAME: 'Pipeline for new version: $CI_COMMIT_REF_NAME'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      variables:
        PIPELINE_NAME: 'MR pipeline: $CI_MERGE_REQUEST_TITLE'
    - if: '$CI_COMMIT_REF_PROTECTED == "true" && $CI_COMMIT_TITLE !~ /^chore\(semver\): Bump.*/'
      variables:
        PIPELINE_NAME: 'Pipeline for protected branch: $CI_COMMIT_REF_NAME'

stages:
  - lint
  - check
  - build
  - test
